services:
  db:
    build:
      context: ./evolab-backend/db
      dockerfile: Dockerfile
    container_name: evolab-db
    environment:
      POSTGRES_DB: evolab
      POSTGRES_USER: evolabuser
      POSTGRES_PASSWORD: changeit
    volumes:
      - evolab-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend-network

  backend:
    build:
      context: ./evolab-backend/
      dockerfile: Dockerfile
    container_name: evolab-backend
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/evolab
      - SPRING_DATASOURCE_USERNAME=evolabuser
      - SPRING_DATASOURCE_PASSWORD=changeit
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    networks:
      - backend-network
      - frontend-network

  frontend:
    build:
      context: ./evolab-frontend/EvoLabAsAService
      dockerfile: Dockerfile
    volumes:
      - ./evolab-frontend/EvoLabAsAService/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    container_name: evolab-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - frontend-network

volumes:
  evolab-db-data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
