# this is called multi-stage build, first we build the app.jar
FROM gradle:8.6-jdk21 AS builder
WORKDIR /app
COPY . .

RUN ./gradlew :evolab-backend:app:bootJar -x test

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=builder /app/evolab-backend/app/build/libs/*-SNAPSHOT.jar app.jar

ENV SPRING_PROFILES_ACTIVE=default
ENV DOCKER_HOST=unix:///var/run/docker.sock

ENTRYPOINT ["java", "-jar", "app.jar"]
