services:
  evolab-db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: evolab-db
    environment:
      POSTGRES_DB: evolab
      POSTGRES_USER: evolabuser
      POSTGRES_PASSWORD: changeit
    ports:
      - "5432:5432"
    volumes:
      - evolab-db-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  evolab-db-data:
    name: evolab-db-data

