server {
    listen 80; # open port 80 for HTTP traffic
    server_name localhost;

    location / {
        root /usr/share/nginx/html; # this is the default location for static files in nginx
        index index.html;
        try_files $uri $uri/ /index.html; # this is important for single-page applications, it tells nginx to serve index.html for any request that doesn't match a file or directory
    }

    location /api/ { # When requests arrive from the frontend, they will be forwarede to the backend service.

        proxy_pass http://backend:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /oauth2/ {
        proxy_pass http://backend:8080/oauth2/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /login/ {
        proxy_pass http://backend:8080/login/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
