@baseUrl = http://localhost:8080
@token = fFl49cYBT8P2d4xhVusV7V1pQ46kuWchkFafSgnCVws=
@userIdToDelete = 8
@localEmail = Teste3@evolab.dev
@localPassword = 12345
@nome = Teste
@emailTeste = pedrofdd@gmail.com
@openAIKey = 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
@geminiKey = AIzaSyCovmLsHKncRg7gtXmWhWpMDvsKKGfgOww
@configId = 5
@llmCredentialId = 4

### -------------------- USER AUTHENTICATION TESTS --------------------

### Criar utilizador local
POST {{baseUrl}}/api/users/local
Content-Type: application/json

{
  "name": "teste",
  "email": "{{emailTeste}}",
  "password": "{{localPassword}}"
}

### http://localhost:8080/oauth2/authorization/google
// Este é o endpoint para autenticação via google, quando concluido, redireciona automaticamete para o endpoint /me


### Obter token (login local)
POST {{baseUrl}}/api/users/token
Content-Type: application/json

{
  "email": "{{emailTeste}}",
  "password": "{{localPassword}}"
}


### Obter utilizador autenticado
GET {{baseUrl}}/api/me
Authorization: Bearer {{token}}

### Logout
POST {{baseUrl}}/api/logout
Authorization: Bearer {{token}}

### Listar todos os users
GET http://localhost:8080/api/users

### Apagar user por id
DELETE {{baseUrl}}/api/users/{{userIdToDelete}}
Authorization: Bearer {{token}}

### -------------------- LLM CREDENTIALS TESTS --------------------

### Criar OPENAI credencial
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "OPENAI",
  "apiKey": "{{openAIKey}}"
}


### Criar OPENAI com formato de chave inválido (Sem 'sk-')
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "OPENAI",
  "apiKey": "1234567890abcdef"
}

### [ERRO] Criar OPENAI com chave falsa (formato correto 'sk-', falha na API da OpenAI)
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "OPENAI",
  "apiKey": "sk-1234fakekeyNaoVaiFuncionar"
}

### Criar GEMINI credencial
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "GEMINI",
  "apiKey": "{{geminiKey}}"
}

### Criar GEMINI com formato inválido
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "GEMINI",
  "apiKey": "gemini-key-invalida"
}

### Criar Credencial para LLM Não Suportado (ex: ANTHROPIC)
POST {{baseUrl}}/api/llm-credentials
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "llm": "ANTHROPIC",
  "apiKey": "sk-ant-1234"
}

### Ler as minhas Credenciais LLM (Verificar se criaram com sucesso)
GET {{baseUrl}}/api/llm-credentials
Authorization: Bearer {{token}}


### Obter todas as credenciais LLM (Admin)
GET {{baseUrl}}/api/llm-credentials/all


### Apagar uma determinada credencial LLM por ID
DELETE {{baseUrl}}/api/llm-credentials/7
Authorization: Bearer {{token}}

### -------------------- CONFIG TESTS --------------------

### Criar Config
POST {{baseUrl}}/api/configs
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "projectId": 5,
  "llmCredentialsId": {{llmCredentialId}},
  "modelName": "gpt-4.1-mini",
  "maxIter": 20,
  "checkPointInterval": 5,
  "additionalParams": {
    "llm.temperature": "0.7",
    "database.population_size": "100"
  }
}

### Ler Config por ID
GET {{baseUrl}}/api/configs/{{configId}}
Authorization: Bearer {{token}}

### Ler todas as minhas Configs
GET {{baseUrl}}/api/configs/me
Authorization: Bearer {{token}}

### Update Config
PUT {{baseUrl}}/api/configs/{{configId}}
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "modelName": "gpt-4.1",
  "maxIter": 30,
  "checkPointInterval": 10,
  "additionalParams": {
    "llm.temperature": "0.6",
    "database.population_size": "150"
  }
}

### -------------------- PROJECT TESTS --------------------

### Criar Project sem configId,initial Program e evaluatorCode (deve aceitar null e criar projeto com valores default)
POST {{baseUrl}}/api/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Meu Primeiro Projeto",
  "description": "Um projeto de teste EvoLab",
  "configId": null,
  "initialProgram": null,
  "evaluatorCode": null
}

### Criar Project sem configId
POST {{baseUrl}}/api/projects
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Meu Primeiro Projeto",
  "description": "Um projeto de teste EvoLab",
  "configId": null,
  "initialProgram": "def hello():\n    print('hello world')",
  "evaluatorCode": "def evaluate():\n    return True"
}


### Ler todos os meus Projetos
GET {{baseUrl}}/api/projects/me
Authorization: Bearer {{token}}

### Ler todos os Projetos globais
GET {{baseUrl}}/api/projects
Authorization: Bearer {{token}}

### Ler Projeto por ID
GET {{baseUrl}}/api/projects/1
Authorization: Bearer {{token}}

### Update Project Details (Substituir parâmetros)
PUT {{baseUrl}}/api/projects/4
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Projeto Atualizado",
  "description": "Nova descrição para o projeto",
  "initialProgram": "def hello():\n    print('hello mundo update')",
  "evaluatorCode": "def evaluate():\n    return False",
  "configId": 1
}

### Iniciar Experimentacao de um Projeto
POST {{baseUrl}}/api/projects/5/start
Authorization: Bearer {{token}}

### Apagar um Projeto
DELETE {{baseUrl}}/api/projects/1
Authorization: Bearer {{token}}

### Atualizar Status do Projeto (Usado pelo Worker - normalmente sem Auth ou regras definidas)
PUT {{baseUrl}}/api/projects/1/status
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "RUNNING"
}
